from models import Box

CUBENESS_THRESHOLD = 0.00

BOX_LIMIT = Box(x=400, y=400, z=400)

W_FLAT = 10.0
W_PYRAMID = 7.0
W_GRAVITY = 5.0  # 5.0
W_EXCEED_PENALTY = 2
W_FRAGILITY = 10.0

MAX_FREE_VOL_RATIO = 2  # box volume <= this * total product volume
MAX_FREE_VOL = 0.5  # max fraction of free space in a box

SEP_WEIGHT_THRESHOLD = 10.0
SEP_WEIGHT_RATIO = 5.0
SEP_HEAVY_FLOOR = 0.5
SEP_MAX_PER_BIN = 7

GEN_MIN_PACKAGES = GEN_MAX_PACKAGES = 20
GEN_ORDERS = 20
GEN_ORDER_PARAM = 0.5
GEN_SIZE_INDEX = 0.0
GEN_WEIGHT_INDEX = 0.0


BOX_W_BIN = 1000
BOX_W_VOL = 1.0

GUR_TIME_LIMIT = 1000


VIS_FIG_SIZE = (13, 8)
VIS_BOX_ALPHA = 0.1
VIS_PACKAGE_ALPHA_MIN = 0.3
VIS_PACKAGE_ALPHA_MAX = 0.9
